namePrefix: "ginkgo"
client: "kube"

# The file to write the test results to.
resultsFile: "results.json"

# If set, only scenarios that failed in a previous run will be executed.
retryFailedScenarios: false

# # If set, the tests will be run in a dual-stack environment.
# dualStackEnabled: false

# # If set, the tests will be run with Konnectivity enabled.
# # TODO: is this the only supported option?
# konnectivityEnabled: true

# If set, the tests will include a cluster update.
testClusterUpdate: false

# Cluster settings
keepFailedClustersAfterTests: true
# usercluster machinedeployment replicas
nodeCount: 2

# Paths
reportsRoot: "_reports"
logDirectory: "_logs"

# Kubermatic settings
kubermaticNamespace: "kubermatic"
kubermaticSeedName: "kubermatic"
kubermaticProject: "" # will be created if empty

secrets:
  kubevirt:
    kkpDatacenter: "kubevirt"
    kubeconfigFile: "/home/soer3n/vscode/mybackup/kubermatic-work/local-kkp"

# A list of Kubernetes releases to test.
releases:
# - "1.32.1"
- "1.33.2"
# - "1.34.1"

# A list of enabled operating system distributions.
enableDistributions:
- ubuntu
# - rockylinux

excluded:
  datacenterDescriptions:
  - "with match subnet and storage location enabled"
  - "with match subnet and storage location disabled"
  - "with default instance types enabled"
  - "with default instance types disabled"
  - "with default preferences types enabled"
  - "with default preferences types disabled"
  - "with ccm zone and region enabled"
  - "with ccm zone and region disabled"
  - "with ccm load balancer enabled"
  - "with ccm load balancer disabled"
  - "with use pod resources cpu enabled"
  - "with use pod resources cpu disabled"
  - "with dns policy set to Default"
  - "with dns policy set to None"
  - "with dns policy set to ClusterFirstWithHostNet"
  - "with images from container disk"
  - "with default preferences types disabled"
  - "with default preferences types enabled"
  - "with default instance types disabled"
  - "with default instance types enabled"
  - "with eviction strategy set to live-migrate"
  - "with eviction strategy set to external"

  clusterDescriptions:
  - "with different update window"
  - "with user ssh key agent enabled"
  - "with audit logging enabled"

  machineDescriptions:
  - "with 8192Mi memory"
  - "with 4 CPUs"
  - "with primary disk OS image from an HTTP source"
  - "with primary disk OS image from a container"
  - "with custom cpu and memory"
  - "with a secondary disk"
  - "with topology spread constraint set to DoNotSchedule"
  - "with topology spread constraint on hostname"
  - "with empty node affinity preset type"
  - "with node affinity preset values"
  - "with node affinity preset key"
  - "with node affinity for hostname node-01"

# included:
#   datacenterDescriptions:
#   - "with match subnet and storage location enabled"
#   - "with match subnet and storage location disabled"
#   - "with eviction strategy set to live-migrate"
#   - "with eviction strategy set to external"

#   clusterDescriptions:
#   - "with user ssh key agent enabled"

#   machineDescriptions:
#   - "with 8192Mi memory"
#   - "with 4 CPUs"
#   - "with primary disk OS image from an HTTP source"
#   - "with primary disk OS image from a container"
#   - "with a secondary disk"
#   - "with topology spread constraint set to DoNotSchedule"
#   - "with topology spread constraint on hostname"
