---
apiVersion: v1
kind: Service
metadata:
  name: conformance-seed-cp-lb
  namespace: conformance-tester
  annotations:
    metallb.io/ip-allocated-from-pool: default
    metallb.io/address-pool: default
    # ovn.kubernetes.io/service_external_ip_from_subnet: external
    # ovn.kubernetes.io/vpc: ovn-cluster
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 6443
    targetPort: 6443
  - name: ssh
    port: 22
    targetPort: 22
  selector:
    kubevirt.io/vmpool: conformance-tester-kkp-cp-pool

---
apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: conformance-tester-kkp-cp-pool
  namespace: conformance-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      kubevirt.io/vmpool: conformance-tester-kkp-cp-pool
  virtualMachineTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmpool: conformance-tester-kkp-cp-pool
    spec:
      dataVolumeTemplates:
      - metadata:
          creationTimestamp: null
          name: conformance-tester-kkp-cp-pool-dv
        spec:
          source:
            http:
              url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
          storage:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 40G
            storageClassName: longhorn
      runStrategy: Always
      template:
        metadata:
          creationTimestamp: null
          labels:
            kubevirt.io/vmpool: conformance-tester-kkp-cp-pool
          annotations:
            kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        spec:
          domain:
            cpu:
              cores: 2
            devices:
              disks:
              - disk:
                  bus: virtio
                name: datavolumedisk
              - disk:
                  bus: virtio
                name: cloudinitdisk
            machine:
              type: q35
            resources:
              limits:
                memory: 8G
              requests:
                memory: 8G
          terminationGracePeriodSeconds: 0
          volumes:
          - dataVolume:
              name: conformance-tester-kkp-cp-pool-dv
            name: datavolumedisk
          - cloudInitNoCloud:
              userData: |
                #cloud-config
                users:
                - groups: users,admin,docker,sudo
                  name: kubeone
                  ssh_authorized_keys:
                  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDhusROKx37AKaX/p+VTsWDNX/EYNC2PgANrat0XN9I4FP6p8DgwcHwgDubm2qNgfGFVkHBXydilh2KpFZabBZP4TcaufCe9PszE2NIIeD16u9UV/GoFiaOg3o5FskEOgA9CQr7+5NbPXR7jUdk4LmuM0Zu84tjiqfM0aUvt2U4qgPpCZ5xTEeVlNnN9n/5pBOAgZvJ1Fcjspzr/55vDeUN/4aDTmnongEIUn88bZkAyZVSeF5dmGObx5yv9WbaaP3kDD6wXOlWEwwcmyuGb3npviJcAGFvvtfz6NAnr0DXyvloGBUKqtVrBzUex6MBUKL/j9JHAEOlN40unL1HC13TJFhmZdljhfaTu6Q/adTbPTL9Y1D2ZBZ0ot52+MyBUQABShER7B0JzZ1BNYF57/PXMk1cLQA3tGUn8xzS65g5+9dh/KX+LkpRT3HAFS72BWDxom5FOwGlsT/I6hBQb0O2ygT7OA1FFsb7IuN5znLccNcUYJLuoiBPJZ5JwGFHDik= soer3n@tux-soer3n"
                  lock-passwd: true
                  ssh_pwauth: False
                  chpasswd: { expire: False }
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
            name: cloudinitdisk